---
- name: Start monitoring services
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring__dir }}"
    state: present
    remove_orphans: yes

- name: Restart Nginx
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring__dir }}"
    services:
      - nginx
    state: restarted

- name: Restart Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring__dir }}"
    services:
      - grafana
    state: restarted

- name: Restart Prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring__dir }}"
    services:
      - prometheus
    state: restarted

- name: Restart Alertmanager
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring__dir }}"
    services:
      - alertmanager
    state: restarted

- name: Restart Loki
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring__dir }}"
    services:
      - loki
    state: restarted
