---
- hosts: production
  become: true
  vars:
    # Grafana settings
    monitoring__grafana_admin_user: "admin"
    monitoring__grafana_admin_password: "admin123"
    
    # Prometheus auth
    monitoring__prometheus_basic_auth_username: "prometheus"
    monitoring__prometheus_basic_auth_password: "prometheus123"
    
    # Loki auth
    monitoring__loki_basic_auth_username: "loki"
    monitoring__loki_basic_auth_password: "loki123"
    
    # MinIO settings (credentials)
    monitoring__minio_access_key: "observability-stack-user"
    monitoring__minio_secret_key: "SbpAjUtQevfZQJRkSxy5cGz8"
    monitoring__loki_bucket_name: "observability-stack-bucket"
    
  roles:
    - monitoring
